//
// Generated file, do not edit! Created by nedtool 5.6 from apps/sateliteudpapp/packet-mariese-cenario/MessageObjeto.msg.
//

#ifndef __INET_MESSAGEOBJETO_M_H
#define __INET_MESSAGEOBJETO_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class MessageObjeto;
} // namespace inet

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet


namespace inet {

// cplusplus {{
#include "inet/common/packet/Packet.h"
#include "inet/common/geometry/common/Coord.h"
// }}

/**
 * Class generated from <tt>apps/sateliteudpapp/packet-mariese-cenario/MessageObjeto.msg:29</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class MessageObjeto extends FieldsChunk
 * {
 *     int portaCarro;
 *     string clientAddr;
 *     long videoId;
 *     long idObj;
 *     double tempDetect;
 *     long obDetect;
 *     long prioridade;
 *     long TempoDeVida;
 *     long obSize;
 * }
 * </pre>
 */
class MessageObjeto : public ::inet::FieldsChunk
{
  protected:
    int portaCarro = 0;
    omnetpp::opp_string clientAddr;
    long videoId = 0;
    long idObj = 0;
    double tempDetect = 0;
    long obDetect = 0;
    long prioridade = 0;
    long TempoDeVida = 0;
    long obSize = 0;

  private:
    void copy(const MessageObjeto& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MessageObjeto&);

  public:
    MessageObjeto();
    MessageObjeto(const MessageObjeto& other);
    virtual ~MessageObjeto();
    MessageObjeto& operator=(const MessageObjeto& other);
    virtual MessageObjeto *dup() const override {return new MessageObjeto(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPortaCarro() const;
    virtual void setPortaCarro(int portaCarro);
    virtual const char * getClientAddr() const;
    virtual void setClientAddr(const char * clientAddr);
    virtual long getVideoId() const;
    virtual void setVideoId(long videoId);
    virtual long getIdObj() const;
    virtual void setIdObj(long idObj);
    virtual double getTempDetect() const;
    virtual void setTempDetect(double tempDetect);
    virtual long getObDetect() const;
    virtual void setObDetect(long obDetect);
    virtual long getPrioridade() const;
    virtual void setPrioridade(long prioridade);
    virtual long getTempoDeVida() const;
    virtual void setTempoDeVida(long TempoDeVida);
    virtual long getObSize() const;
    virtual void setObSize(long obSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MessageObjeto& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MessageObjeto& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_MESSAGEOBJETO_M_H

