//
// Generated file, do not edit! Created by nedtool 5.6 from apps/sateliteudpapp/packet-mariese-cenario/SateliteMessage.msg.
//

#ifndef __INET_SATELITEMESSAGE_M_H
#define __INET_SATELITEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class SateliteMessage;
} // namespace inet

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet


namespace inet {

// cplusplus {{
#include "inet/common/packet/Packet.h"
#include "inet/common/geometry/common/Coord.h"
// }}

/**
 * Class generated from <tt>apps/sateliteudpapp/packet-mariese-cenario/SateliteMessage.msg:29</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class SateliteMessage extends FieldsChunk
 * {
 *     long tamanhoPacote;
 *     int portaCarro;
 *     string clientAddr;
 *     short tosEscolhido;
 *     double distAntenna;
 *     double vel;
 *     double tempoEntrada;
 *     int ri;
 *     double coordX;
 *     double coordY;
 *     long id;
 *     long idObj;
 *     double tempDetect;
 *     long obDetect;
 *     long prioridade;
 *     long TempoDeVida;
 *     long obSize;
 *     double coordObjX;
 *     double coordObjY;
 * }
 * </pre>
 */
class SateliteMessage : public ::inet::FieldsChunk
{
  protected:
    long tamanhoPacote = 0;
    int portaCarro = 0;
    omnetpp::opp_string clientAddr;
    short tosEscolhido = 0;
    double distAntenna = 0;
    double vel = 0;
    double tempoEntrada = 0;
    int ri = 0;
    double coordX = 0;
    double coordY = 0;
    long id = 0;
    long idObj = 0;
    double tempDetect = 0;
    long obDetect = 0;
    long prioridade = 0;
    long TempoDeVida = 0;
    long obSize = 0;
    double coordObjX = 0;
    double coordObjY = 0;

  private:
    void copy(const SateliteMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SateliteMessage&);

  public:
    SateliteMessage();
    SateliteMessage(const SateliteMessage& other);
    virtual ~SateliteMessage();
    SateliteMessage& operator=(const SateliteMessage& other);
    virtual SateliteMessage *dup() const override {return new SateliteMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual long getTamanhoPacote() const;
    virtual void setTamanhoPacote(long tamanhoPacote);
    virtual int getPortaCarro() const;
    virtual void setPortaCarro(int portaCarro);
    virtual const char * getClientAddr() const;
    virtual void setClientAddr(const char * clientAddr);
    virtual short getTosEscolhido() const;
    virtual void setTosEscolhido(short tosEscolhido);
    virtual double getDistAntenna() const;
    virtual void setDistAntenna(double distAntenna);
    virtual double getVel() const;
    virtual void setVel(double vel);
    virtual double getTempoEntrada() const;
    virtual void setTempoEntrada(double tempoEntrada);
    virtual int getRi() const;
    virtual void setRi(int ri);
    virtual double getCoordX() const;
    virtual void setCoordX(double coordX);
    virtual double getCoordY() const;
    virtual void setCoordY(double coordY);
    virtual long getId() const;
    virtual void setId(long id);
    virtual long getIdObj() const;
    virtual void setIdObj(long idObj);
    virtual double getTempDetect() const;
    virtual void setTempDetect(double tempDetect);
    virtual long getObDetect() const;
    virtual void setObDetect(long obDetect);
    virtual long getPrioridade() const;
    virtual void setPrioridade(long prioridade);
    virtual long getTempoDeVida() const;
    virtual void setTempoDeVida(long TempoDeVida);
    virtual long getObSize() const;
    virtual void setObSize(long obSize);
    virtual double getCoordObjX() const;
    virtual void setCoordObjX(double coordObjX);
    virtual double getCoordObjY() const;
    virtual void setCoordObjY(double coordObjY);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SateliteMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SateliteMessage& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_SATELITEMESSAGE_M_H

