//
// Generated file, do not edit! Created by nedtool 5.6 from apps/sateliteudpapp/packet-mariese-cenario/ServerConnMessage.msg.
//

#ifndef __INET_SERVERCONNMESSAGE_M_H
#define __INET_SERVERCONNMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class ServerConnMessage;
} // namespace inet

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet


namespace inet {

// cplusplus {{
#include "inet/common/packet/Packet.h"
// }}

/**
 * Class generated from <tt>apps/sateliteudpapp/packet-mariese-cenario/ServerConnMessage.msg:27</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class ServerConnMessage extends FieldsChunk
 * {
 *     bool confirmacaoRequest;
 *     string srcName;
 *     int portaCarro;
 *     string clientAddr;
 *     short tosEscolhido;
 *     double capacidadeMax = -1;
 *     long tamanhoPacote = -1;
 *     double distAntenna = -1;
 *     double vel = -1;
 *     double tempoEntrada = -1;
 *     int ri = -1;
 *     double coordX = 0;
 *     double coordY = 0;
 *     long tempoCon = -1;
 *     long videoId;
 *     long idObj = -1;
 *     double tempDetect = -1;
 *     long obDetect = -1;
 *     long prioridade = -1;
 *     long TempoDeVida = -1;
 *     long obSize = -1;
 *     double coordObjX = 0;
 *     double coordObjY = 0;
 * }
 * </pre>
 */
class ServerConnMessage : public ::inet::FieldsChunk
{
  protected:
    bool confirmacaoRequest = false;
    omnetpp::opp_string srcName;
    int portaCarro = 0;
    omnetpp::opp_string clientAddr;
    short tosEscolhido = 0;
    double capacidadeMax = -1;
    long tamanhoPacote = -1;
    double distAntenna = -1;
    double vel = -1;
    double tempoEntrada = -1;
    int ri = -1;
    double coordX = 0;
    double coordY = 0;
    long tempoCon = -1;
    long videoId = 0;
    long idObj = -1;
    double tempDetect = -1;
    long obDetect = -1;
    long prioridade = -1;
    long TempoDeVida = -1;
    long obSize = -1;
    double coordObjX = 0;
    double coordObjY = 0;

  private:
    void copy(const ServerConnMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ServerConnMessage&);

  public:
    ServerConnMessage();
    ServerConnMessage(const ServerConnMessage& other);
    virtual ~ServerConnMessage();
    ServerConnMessage& operator=(const ServerConnMessage& other);
    virtual ServerConnMessage *dup() const override {return new ServerConnMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getConfirmacaoRequest() const;
    virtual void setConfirmacaoRequest(bool confirmacaoRequest);
    virtual const char * getSrcName() const;
    virtual void setSrcName(const char * srcName);
    virtual int getPortaCarro() const;
    virtual void setPortaCarro(int portaCarro);
    virtual const char * getClientAddr() const;
    virtual void setClientAddr(const char * clientAddr);
    virtual short getTosEscolhido() const;
    virtual void setTosEscolhido(short tosEscolhido);
    virtual double getCapacidadeMax() const;
    virtual void setCapacidadeMax(double capacidadeMax);
    virtual long getTamanhoPacote() const;
    virtual void setTamanhoPacote(long tamanhoPacote);
    virtual double getDistAntenna() const;
    virtual void setDistAntenna(double distAntenna);
    virtual double getVel() const;
    virtual void setVel(double vel);
    virtual double getTempoEntrada() const;
    virtual void setTempoEntrada(double tempoEntrada);
    virtual int getRi() const;
    virtual void setRi(int ri);
    virtual double getCoordX() const;
    virtual void setCoordX(double coordX);
    virtual double getCoordY() const;
    virtual void setCoordY(double coordY);
    virtual long getTempoCon() const;
    virtual void setTempoCon(long tempoCon);
    virtual long getVideoId() const;
    virtual void setVideoId(long videoId);
    virtual long getIdObj() const;
    virtual void setIdObj(long idObj);
    virtual double getTempDetect() const;
    virtual void setTempDetect(double tempDetect);
    virtual long getObDetect() const;
    virtual void setObDetect(long obDetect);
    virtual long getPrioridade() const;
    virtual void setPrioridade(long prioridade);
    virtual long getTempoDeVida() const;
    virtual void setTempoDeVida(long TempoDeVida);
    virtual long getObSize() const;
    virtual void setObSize(long obSize);
    virtual double getCoordObjX() const;
    virtual void setCoordObjX(double coordObjX);
    virtual double getCoordObjY() const;
    virtual void setCoordObjY(double coordObjY);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ServerConnMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ServerConnMessage& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_SERVERCONNMESSAGE_M_H

